(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();const l=document.getElementById("task-list"),m=document.getElementById("task-form"),f=document.getElementById("themeToggle");document.querySelector(".header-form-btn");const a=document.body;function g(s){let e=JSON.parse(localStorage.getItem("tasks"))||[];e.push(s),localStorage.setItem("tasks",JSON.stringify(e))}function p(s){const o=(JSON.parse(localStorage.getItem("tasks"))||[]).filter((i,t)=>t!==s);localStorage.setItem("tasks",JSON.stringify(o))}function k(s){const o=(JSON.parse(localStorage.getItem("tasks"))||[]).map(({title:i,description:t})=>`<li class="task-list-item">
        <button class="task-list-item-btn">Delete</button>
        <h3>${i}</h3>
        <p>${t}</p>
      </li>`).join(`
`);l.insertAdjacentHTML("beforeend",o)}function L({title:s,description:e}){const o=`<li class="task-list-item">
        <button class="task-list-item-btn">Delete</button>
        <h3>${s}</h3>
        <p>${e}</p>
      </li>`;l.insertAdjacentHTML("beforeend",o)}k();m.addEventListener("submit",s=>{s.preventDefault();const e=s.target.taskName.value.trim(),o=s.target.taskDescription.value.trim();if(console.log(e),console.log(o),!e||!o)return alert("Заповніть усі поля форми!");L({title:e,description:o}),g({title:e,description:o}),m.reset()});l.addEventListener("click",s=>{if(s.target.classList.contains("task-list-item-btn")){const e=s.target.closest(".task-list-item"),o=[...l.children].indexOf(e);e.remove(),p(o)}});const u="theme",n={LIGHT:"theme-light",DARK:"theme-dark"},d=localStorage.getItem(u);d===n.LIGHT||d===n.DARK?a.classList.add(d):a.classList.add(n.DARK);f.addEventListener("click",()=>{const s=a.classList.contains(n.DARK)?n.LIGHT:n.DARK;a.classList.toggle(n.LIGHT),a.classList.toggle(n.DARK),localStorage.setItem(u,s)});
//# sourceMappingURL=index.js.map
